[2016-05-26 00:42:15,726] WARNING : Session data corrupted
[2016-05-26 00:42:15,775] ERROR : Internal Server Error: /
Traceback (most recent call last):
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/template/base.py", line 1049, in render
    return render_value_in_context(output, context)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/template/base.py", line 1026, in render_value_in_context
    value = force_text(value)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/db/models/query.py", line 234, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 837, in execute_sql
    sql, params = self.as_sql()
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 382, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 49, in pre_sql_setup
    order_by = self.get_order_by()
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 295, in get_order_by
    field, self.query.get_meta(), default_order=asc))
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 566, in find_ordering_name
    field, targets, alias, joins, path, opts = self._setup_joins(pieces, opts, alias)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 599, in _setup_joins
    pieces, opts, alias)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1405, in setup_joins
    names, opts, allow_many, fail_on_missing=True)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'expirydate' into field. Choices are: EXPIRYDATE, JOBREF, JOBURL, JOB_SUMMARY, LANGUAGE, NAME, POSITION, POSTDATE, SALARYMAX, SALARYMIN, SALARYTYPE, description, id, slug, tweeted
[2016-05-26 00:42:39,373] WARNING : Session data corrupted
[2016-05-26 00:42:39,395] ERROR : Internal Server Error: /jobs/
Traceback (most recent call last):
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/rest_framework/fields.py", line 401, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/rest_framework/fields.py", line 76, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'Emploi' object has no attribute 'description'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/home/guinsly/development/public/project/django-ottawa-city-jobs/applications/cityjobs/views.py", line 18, in all_jobs
    return Response(serializers.data)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/rest_framework/serializers.py", line 658, in data
    ret = super(ListSerializer, self).data
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/rest_framework/serializers.py", line 223, in data
    self._data = self.to_representation(self.instance)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/rest_framework/serializers.py", line 598, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/rest_framework/serializers.py", line 598, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/rest_framework/serializers.py", line 447, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/rest_framework/fields.py", line 418, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `description` on serializer `EmploiSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Emploi` instance.
Original exception text was: 'Emploi' object has no attribute 'description'.
[2016-05-26 12:55:43,330] WARNING : Session data corrupted
[2016-05-26 12:57:36,664] WARNING : Session data corrupted
[2016-05-26 12:57:36,891] WARNING : Session data corrupted
[2016-05-26 12:58:20,988] WARNING : Session data corrupted
[2016-05-26 12:58:25,355] WARNING : Session data corrupted
[2016-05-26 12:58:31,552] WARNING : Session data corrupted
[2016-05-26 13:03:55,327] WARNING : Not Found: /emplois/searchJobs
[2016-05-26 13:04:43,358] WARNING : Not Found: /emplois/searchJobs
[2016-05-26 13:11:04,146] WARNING : Not Found: /emplois/searchJobs
[2016-05-26 13:21:23,816] INFO %(lineno)d %(module)s 12704 -1219602688 : Test Django Logging
[2016-05-26 13:21:23,816] INFO %(lineno)d %(module)s 12704 -1219602688 : Something went wrong!
[2016-05-26 13:21:23,816] ERROR %(lineno)d %(module)s 12704 -1219602688 : Test Django Logging
[2016-05-26 13:21:39,003] INFO %(lineno)d %(module)s 12730 -1219168512 : Test Django Logging
[2016-05-26 13:21:39,003] INFO %(lineno)d %(module)s 12730 -1219168512 : Something went wrong!
[2016-05-26 13:21:39,003] ERROR %(lineno)d %(module)s 12730 -1219168512 : Test Django Logging
[2016-05-26 13:21:44,204] INFO %(lineno)d %(module)s 12774 -1219627264 : Test Django Logging
[2016-05-26 13:21:44,204] INFO %(lineno)d %(module)s 12774 -1219627264 : Something went wrong!
[2016-05-26 13:21:44,204] ERROR %(lineno)d %(module)s 12774 -1219627264 : Test Django Logging
[2016-05-26 13:21:44,796] INFO %(lineno)d %(module)s 12802 -1219410176 : Test Django Logging
[2016-05-26 13:21:44,796] INFO %(lineno)d %(module)s 12802 -1219410176 : Something went wrong!
[2016-05-26 13:21:44,797] ERROR %(lineno)d %(module)s 12802 -1219410176 : Test Django Logging
[2016-05-26 13:22:14,494] INFO %(lineno)d %(module)s 12834 -1219492096 : Test Django Logging
[2016-05-26 13:22:14,494] INFO %(lineno)d %(module)s 12834 -1219492096 : Something went wrong!
[2016-05-26 13:22:14,494] ERROR %(lineno)d %(module)s 12834 -1219492096 : Test Django Logging
[2016-05-26 13:22:37,892] INFO %(lineno)d %(module)s 12941 -1219770624 : Something went wrong!
[2016-05-26 13:22:37,892] ERROR %(lineno)d %(module)s 12941 -1219770624 : Test Django Logging
[2016-05-26 13:22:43,846] INFO %(lineno)d %(module)s 12955 -1219422464 : Something went wrong!
[2016-05-26 13:22:43,846] ERROR %(lineno)d %(module)s 12955 -1219422464 : Test Django Logging
[2016-05-26 13:22:54,673] INFO %(lineno)d %(module)s 12992 -1219057920 : Something went wrong!
[2016-05-26 13:22:54,673] ERROR %(lineno)d %(module)s 12992 -1219057920 : Test Django Logging
[2016-05-26 13:23:00,647] ERROR %(lineno)d %(module)s 13010 -1219717376 : Test Django Logging
[2016-05-26 13:23:05,462] ERROR %(lineno)d %(module)s 13010 -1263535296 : Test Django Logging
[2016-05-26 13:23:05,462] INFO %(lineno)d %(module)s 13010 -1263535296 : LIQPAY: API Call from LiqPay: <QueryDict: {}>
[2016-05-26 13:23:28,173] ERROR %(lineno)d %(module)s 13158 -1219729664 : Test Django Logging
[2016-05-26 13:23:50,560] ERROR %(lineno)d %(module)s 13183 -1219799296 : Test Django Logging
[2016-05-26 13:24:01,728] INFO %(lineno)d %(module)s 13210 -1263535296 : Language is set to : FR
[2016-05-26 13:24:51,301] INFO %(lineno)d %(module)s 13361 -1263535296 : Language is set to : FR
[2016-05-26 13:24:51,307] ERROR %(lineno)d %(module)s 13361 -1263535296 : Internal Server Error: /
Traceback (most recent call last):
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/views/generic/list.py", line 159, in get
    self.object_list = self.get_queryset()
  File "/home/guinsly/development/public/project/django-ottawa-city-jobs/applications/emplois/views.py", line 54, in get_queryset
    .order_by('EXPIRYDATE').count())
TypeError: Can't convert 'int' object to str implicitly
[2016-05-26 13:25:17,695] INFO %(lineno)d %(module)s 13409 -1262486720 : Language is set to : FR
[2016-05-26 13:25:17,702] ERROR %(lineno)d %(module)s 13409 -1262486720 : Internal Server Error: /
Traceback (most recent call last):
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guinsly/.pyenv/versions/django1.9.3.4.3/lib/python3.4/site-packages/django/views/generic/list.py", line 159, in get
    self.object_list = self.get_queryset()
  File "/home/guinsly/development/public/project/django-ottawa-city-jobs/applications/emplois/views.py", line 52, in get_queryset
    logger.info('Number of Object retrived : '+ Job.objects.filter(language=self.language(),EXPIRYDATE__gt=datetime.now()).order_by('EXPIRYDATE').count())
TypeError: Can't convert 'int' object to str implicitly
[2016-05-26 13:25:59,575] INFO %(lineno)d %(module)s 13490 -1263535296 : Language is set to : FR
[2016-05-26 13:25:59,581] INFO %(lineno)d %(module)s 13490 -1263535296 : Number of Object retrived : 0
[2016-05-26 13:25:59,581] INFO %(lineno)d %(module)s 13490 -1263535296 : Language is set to : FR
[2016-05-26 13:28:24,671] INFO %(lineno)d %(module)s 13807 -1263535296 : Language is set to : FR
[2016-05-26 13:28:24,678] INFO %(lineno)d %(module)s 13807 -1263535296 : Number of Object retrieved : 0
[2016-05-26 13:28:24,678] INFO %(lineno)d %(module)s 13807 -1263535296 : Language is set to : FR
[2016-05-26 13:28:24,678] INFO %(lineno)d %(module)s 13807 -1263535296 : Language : FR
[2016-05-26 13:28:24,678] INFO %(lineno)d %(module)s 13807 -1263535296 : ExpiryDate2016-05-26 13:28:24.678643
[2016-05-26 13:28:24,678] INFO %(lineno)d %(module)s 13807 -1263535296 : Language is set to : FR
[2016-05-26 13:28:45,371] INFO %(lineno)d %(module)s 13945 -1263535296 : Language is set to : FR
[2016-05-26 13:28:45,378] INFO %(lineno)d %(module)s 13945 -1263535296 : Number of Object retrieved : 0
[2016-05-26 13:28:45,379] INFO %(lineno)d %(module)s 13945 -1263535296 : Language is set to : FR
[2016-05-26 13:28:45,379] INFO %(lineno)d %(module)s 13945 -1263535296 : Language : FR
[2016-05-26 13:28:45,379] INFO %(lineno)d %(module)s 13945 -1263535296 : ExpiryDate : 2016-05-26 13:28:45.379333
[2016-05-26 13:28:45,379] INFO %(lineno)d %(module)s 13945 -1263535296 : Language is set to : FR
[2016-05-26 13:29:17,035] INFO %(funcName) 14100 -1263535296 : Language is set to : FR
[2016-05-26 13:29:17,042] INFO %(funcName) 14100 -1263535296 : Number of Object retrieved : 0
[2016-05-26 13:29:17,043] INFO %(funcName) 14100 -1263535296 : Language is set to : FR
[2016-05-26 13:29:17,043] INFO %(funcName) 14100 -1263535296 : Language : FR
[2016-05-26 13:29:17,043] INFO %(funcName) 14100 -1263535296 : ExpiryDate : 2016-05-26 13:29:17.043284
[2016-05-26 13:29:17,043] INFO %(funcName) 14100 -1263535296 : Language is set to : FR
[2016-05-26 13:29:36,664] INFO %(process)d -1263535296 : Language is set to : FR
[2016-05-26 13:29:36,670] INFO %(process)d -1263535296 : Number of Object retrieved : 0
[2016-05-26 13:29:36,670] INFO %(process)d -1263535296 : Language is set to : FR
[2016-05-26 13:29:36,670] INFO %(process)d -1263535296 : Language : FR
[2016-05-26 13:29:36,670] INFO %(process)d -1263535296 : ExpiryDate : 2016-05-26 13:29:36.670865
[2016-05-26 13:29:36,671] INFO %(process)d -1263535296 : Language is set to : FR
[2016-05-26 13:30:29,940] INFO %(process)d -1263535296 : Language is set to : FR
[2016-05-26 13:30:29,950] INFO %(process)d -1263535296 : Number of Object retrieved : 0
[2016-05-26 13:30:29,950] INFO %(process)d -1263535296 : Language is set to : FR
[2016-05-26 13:30:29,950] INFO %(process)d -1263535296 : Language : FR
[2016-05-26 13:30:29,950] INFO %(process)d -1263535296 : ExpiryDate : 2016-05-26 13:30:29.950641
[2016-05-26 13:30:29,950] INFO %(process)d -1263535296 : Language is set to : FR
[2016-05-26 13:31:20,213] INFO %(process)d -1263535296 : Number of Object retrieved : 0
[2016-05-26 13:31:20,213] INFO %(process)d -1263535296 : Language : FR
[2016-05-26 13:31:20,213] INFO %(process)d -1263535296 : ExpiryDate : 2016-05-26 13:31:20.213971
[2016-05-26 13:31:48,818] INFO %(process)d -1263535296 : Number of Object retrieved : 0
[2016-05-26 13:31:48,818] INFO %(process)d -1263535296 : Language : FR
[2016-05-26 13:31:48,818] INFO %(process)d -1263535296 : ExpiryDate : 2016-05-26 13:31:48.818622
[2016-05-26 13:33:23,516] INFO %(process)d -1294992576 : Number of Object retrieved : 0
[2016-05-26 13:33:23,516] INFO %(process)d -1294992576 : Language : FR
[2016-05-26 13:33:23,516] INFO %(process)d -1294992576 : ExpiryDate : 2016-05-26 13:33:23.516478
[2016-05-26 13:43:25,309] INFO %(process)d -1263535296 : Number of Object retrieved : 98
[2016-05-26 13:43:25,310] INFO %(process)d -1263535296 : Language : FR
[2016-05-26 13:43:25,310] INFO %(process)d -1263535296 : ExpiryDate : 2016-05-26 13:43:25.310350
[2016-05-26 13:43:35,440] INFO %(process)d -1274021056 : Number of Object retrieved : 98
[2016-05-26 13:43:35,440] INFO %(process)d -1274021056 : Language : EN
[2016-05-26 13:43:35,440] INFO %(process)d -1274021056 : ExpiryDate : 2016-05-26 13:43:35.440661
